{% set version = "3.0.0" %}

package:
  name: jupyter-collaboration
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-collaboration/jupyter_collaboration-{{ version }}.tar.gz
  sha256: 79ec00b21fc423c0d5e053568231214fad5151b69813ab2e3809f2e1b7f5082c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python >=3.8
  run:
    - jupyter-collaboration-ui >=1.0.0
    - jupyter-docprovider >=1.0.0
    - jupyter_server_ydoc >=1.0.0
    - python >=3.8

test:
  imports:
    - jupyter_collaboration
  requires:
    - pip
    - jupyterlab
    - m2-grep  # [win]
  commands:
    - pip check
    # server extension
    - jupyter server extension list
    # labextensions
    - jupyter labextension list
    # check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "collaboration-extension.*OK" labextensions
    - grep -iE "docprovider-extension.*OK" labextensions

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: JupyterLab/Jupyter Notebook 7+ Real Time Collaboration extension (metapackage)
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
