{% set version = "3.1.0" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: jupyter-collaboration
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration/jupyter_collaboration-{{ version }}.tar.gz
  sha256: 043986e6fcdd8a4161df8d9716a93ddaafec9a274aa9b503584c7a80e461ee9f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python {{ python_min }}
  run:
    - jupyter_server_ydoc >=1.0.1
    - jupyter-collaboration-ui >=1.0.1
    - jupyter-docprovider >=1.0.1
    - python >={{ python_min }}

test:
  imports:
    - jupyter_collaboration
  requires:
    - jupyterlab
    - pip
    - python {{ python_min }}
    - m2-grep  # [win]
  commands:
    - pip check
    # server extension
    - jupyter server extension list
    # labextensions
    - jupyter labextension list
    # check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "collaboration-extension.*OK" labextensions
    - grep -iE "docprovider-extension.*OK" labextensions

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: JupyterLab/Jupyter Notebook 7+ Real Time Collaboration extension (metapackage)
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
