{% set jupyterlab_version = ">=4.0.5" %}
{% set version = "2.0.0" %}
{% set jupyterlab_version = ">=4.0.5" %}

package:
  name: jupyter-collaboration
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-collaboration/jupyter_collaboration-{{ version }}.tar.gz
  sha256: eed21d0977045f074f80ee47c678c094f19c81567602d50a7ad858ab18a9958f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - jupyterlab {{ jupyterlab_version }}
  run:
    - python >=3.8
    - jupyter_server >=2.0.0,<3.0.0
    - jupyter_ydoc >=1.0.1,<2.0.0
    - ypy-websocket >=0.12.1,<0.13.0
    - jupyter_events >=0.7.0
    - jupyter_server_fileid >=0.7.0,<1
    - jsonschema >=4.18.0
  run_constrained:
    - jupyterlab {{ jupyterlab_version }}

test:
  imports:
    - jupyter_collaboration
  requires:
    - pip
    - jupyterlab
  commands:
    - pip check
    # jupyter_server server extension
    - jupyter server extension list  # [unix]
    - jupyter server extension list 1>server_extensions 2>&1  # [unix]
    - cat server_extensions | grep "jupyter_collaboration.*OK"  # [unix]
    # labextensions
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "collaboration-extension.*OK.*jupyter_collaboration"  # [unix]

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: A Jupyter extension providing support for collaborative features in JupyterLab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyter_collaboration/labextension/static/third-party-licenses.json
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io
  dev_url: https://github.com/jupyterlab/jupyter-collaboration

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
