{% set version = "2.1.4" %}

# the `if` block helps the bot avoid duplicating this line over and over...
{% if 1 %}{% set jupyterlab_version = ">=4.0.5,<4.2" %}{% endif %}

package:
  name: jupyter-collaboration
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-collaboration/jupyter_collaboration-{{ version }}.tar.gz
  sha256: 613df0ad343c8a6b932bccde25bc2c707b5ac2daaca5fd6822d1b330c7e0e62a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - jupyterlab {{ jupyterlab_version }}
  run:
    - python >=3.8
    - jupyter_server >=2.0.0,<3.0.0
    - jupyter_ydoc >=2.1.2,<3.0.0
    - pycrdt
    - pycrdt-websocket >=0.15.0,<0.16.0
    - jupyter_events >=0.10.0
    - jupyter_server_fileid >=0.7.0,<1
    - jsonschema >=4.18.0
  run_constrained:
    - jupyterlab {{ jupyterlab_version }}

test:
  imports:
    - jupyter_collaboration
  requires:
    - pip
    - jupyterlab
    - m2-grep  # [win]
  commands:
    - pip check
    # server extension
    - jupyter server extension list
    # labextensions
    - jupyter labextension list
    # check
    - jupyter server extension list 1>server_extensions 2>&1
    - jupyter labextension list 1>labextensions 2>&1 
    - grep -iE "jupyter_collaboration.*OK" server_extensions
    - grep -iE "collaboration-extension.*OK.*jupyter_collaboration" labextensions

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  summary: A Jupyter extension providing support for collaborative features in JupyterLab
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyter_collaboration/labextension/static/third-party-licenses.json
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
