# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.1.2"

package:
  name: jupyter-collaboration
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration/jupyter_collaboration-${{ version }}.tar.gz
  sha256: 44fc022b4a4f17362a4ba80a50592f4599ce3c04ef65f5cd2b5ed503a362db41

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - jupyter_server_ydoc >=1.1.2,<2
    - jupyter-collaboration-ui >=1.1.2,<2
    - jupyter-docprovider >=1.1.2,<2
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyter_collaboration
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.14.*
  - requirements:
      run:
        - jupyterlab
        - python ${{ python_min }}.*
    script:
      - jupyter server extension list
      - jupyter labextension list --debug
      - jupyter labextension list 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'collaboration-extension.*OK', v)"
      - jupyter labextension list 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'docprovider-extension.*OK', v)"
about:
  summary: JupyterLab/Jupyter Notebook 7+ Real Time Collaboration extension (metapackage)
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyterlab/jupyter-collaboration
  documentation: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
