# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.2.0"
  python_check_max: "3.14"

package:
  name: jupyter-collaboration
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration/jupyter_collaboration-${{ version }}.tar.gz
  sha256: b81d4738da31ea0f1df95b39dbc101ca23f9d47661ee6413bc9651388a843416

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - jupyter_server_ydoc >=2.2.0,<3
    - jupyter-collaboration-ui >=2.2.0,<3
    - jupyter-docprovider >=2.2.0,<3
    - jupyterlab >=4.5.0,<5.0.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyter_collaboration
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - jupyterlab
        - python ${{ python_min }}.*
    script:
      - jupyter server extension list
      - jupyter labextension list --debug
      - jupyter labextension list 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'collaboration-extension.*OK', v)"
      - jupyter labextension list 2>&1 | python -c "import re, sys; v = sys.stdin.read(); assert re.search(r'docprovider-extension.*OK', v)"
about:
  summary: JupyterLab/Jupyter Notebook 7+ Real Time Collaboration extension (metapackage)
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyterlab/jupyter-collaboration
  documentation: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
