# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.0.1"

package:
  name: jupyter-collaboration
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-collaboration/jupyter_collaboration-${{ version }}.tar.gz
  sha256: a19971044e1eb93560c7ae1b7219f53e409b65d12e9e06ca4b52d07ea7d6775f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling >=1.4.0
    - pip
    - python ${{ python_min }}.*
  run:
    - jupyter_server_ydoc >=2.0.1,<3
    - jupyter-collaboration-ui >=2.0.1,<3
    - jupyter-docprovider >=2.0.1,<3
    - jupyterlab >=4.4.0,<5.0.0
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyter_collaboration
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - jupyterlab
        - python ${{ python_min }}.*
        - if: win
          then: m2-grep
    script:
      - jupyter server extension list
      - jupyter labextension list
      - jupyter labextension list 1>labextensions 2>&1
      - grep -iE "collaboration-extension.*OK" labextensions
      - grep -iE "docprovider-extension.*OK" labextensions

about:
  summary: JupyterLab/Jupyter Notebook 7+ Real Time Collaboration extension (metapackage)
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyterlab/jupyter-collaboration
  documentation: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - hbcarlos
    - martinRenou
    - fcollonval
    - davidbrochart
    - conda-forge/jupyterlab
